# this is a config for soc generator.
[meta]
name    = "soc"
user    = "oscc"
process = "t28"
date    = "202404"
gen_dir = "gen"
version = "0.1"
author  = "demo"

[core]
path = "core"
file = "demo.v"
top  = "demo"

[ram]
path = "ram"

[filelist]
path = "filelist"
be = "be"
sim = "sim"

[top]
path = "top"

[tb]
path = "tb"

[sim]
path = "sim"

[rcu]
path = "rcu"
pll_num = 1
bypass  = true
[rcu.core_clk]
freq_list = [25, 50, 100, 150, 200, 250, 300]
[rcu.perip_clk]
freq_list = [100]

[bus]
path = "bus"
[bus.mst]
num = 1
[[bus.mst.list]]
name = "core_master"
prot = "axi4"
[bus.slv]
num = 3
[[bus.slv.list]]
name = "uart_slave"
prot = "apb4"
burst = false
[[bus.slv.list]]
name = "spi_slave"
prot = "apb4"
burst = false
[[bus.slv.list]]
name = "chiplink_slave"
prot = "axi4"

[ip]
path = "perip"
perip = ["archinfo", "pwm", "rng", "uart"]
# tag and commit field is optional
[ip.archinfo]
branch = "main"
commit = "lastest"
pinmux = false